version: "3.3"

services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=flask_db
      - POSTGRES_USER=flask_orm
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
    networks:
      - internal

  backend:
    image: srbgd/backend:latest
    ports:
      - 5000:5000
    networks:
      - internal
    depends_on:
      - db
    environment:
      - DB_HOST=db
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal
      - external
    depends_on:
      - backend


networks:
  internal:
    internal: true
    driver: bridge
  external: